IF(NOT STM32_CHIP_TYPE)
	MESSAGE(FATAL_ERROR "Select your stm32 chip using STM32_CHIP_TYPE variable. (HD, HD_VL, MD, MDP, MD_VL, LD, LD_VL, XD, CL)")
ENDIF()

IF(NOT STM32_FAMILY)
	SET(STM32_FAMILY "F10x")
	MESSAGE(STATUS "No STM32_FAMILY specified, using default: " ${STM32_FAMILY})
ENDIF()
STRING(TOLOWER "${STM32_FAMILY}" STM32_FAMILY_L)
STRING(TOUPPER "${STM32_FAMILY}" STM32_FAMILY_U)
STRING(TOUPPER "${STM32_CHIP_TYPE}" STM32_CHIP_TYPE)

IF(STM32_FAMILY_U STREQUAL "F10X")
	SET(DENSITY_LIST_U HD HD_VL MD MD_VL LD LD_VL XD CL)
ELSEIF(STM32_FAMILY_U STREQUAL "L1XX")
	SET(DENSITY_LIST_U HD MD MDP)
ELSE()
	MESSAGE(FATAL_ERROR "Unknown stm32 family: STM32" ${STM32_FAMILY_U})
ENDIF()

FOREACH(DENSITY_U ${DENSITY_LIST_U})
	IF(DENSITY_U STREQUAL STM32_CHIP_TYPE)
		STRING(TOLOWER "${STM32_CHIP_TYPE}" STM32_CHIP_TYPE_LOWER)
	ENDIF()
ENDFOREACH(DENSITY_U)

IF(NOT STM32_CHIP_TYPE_LOWER)
	MESSAGE(FATAL_ERROR "Specified wrong chip type: there is no ${STM32_CHIP_TYPE} type in the STM32${STM32_FAMILY_U} family")
ENDIF()


SET(CMSIS_LIB_NAME stm32${STM32_FAMILY_L}_cmsis_${STM32_CHIP_TYPE_LOWER})
SET(CMSIS_STARTUP_NAME startup_stm32${STM32_FAMILY_L}_${STM32_CHIP_TYPE_LOWER}.s)
SET(STM32_CHIP_DEF "-DSTM32${STM32_FAMILY_U}_${STM32_CHIP_TYPE}")

FIND_PATH(CMSIS_INCLUDE_DIR
	NAMES system_stm32${STM32_FAMILY_L}.h core_cm3.h stm32${STM32_FAMILY_L}.h
	PATH_SUFFIXES include stm32${STM32_FAMILY_L}
)

FIND_LIBRARY(CMSIS_LIBRARIES
	NAMES ${CMSIS_LIB_NAME}
	PATH_SUFFIXES lib
)

FIND_FILE(CMSIS_STARTUP_SOURCE
	${CMSIS_STARTUP_NAME}
	PATHS ${CMAKE_FIND_ROOT_PATH}/share/cmsis/
)

FIND_FILE(CMSIS_LINKER_SCRIPT
	stm32${STM32_FAMILY_L}_flash.ld.in
	PATHS ${CMAKE_FIND_ROOT_PATH}/share/cmsis/
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CMSIS DEFAULT_MSG CMSIS_LIBRARIES CMSIS_INCLUDE_DIR CMSIS_STARTUP_SOURCE CMSIS_LINKER_SCRIPT)

SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${STM32_CHIP_DEF}")
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${STM32_CHIP_DEF}")

FUNCTION(STM32_SET_PARAMS FLASH_SIZE RAM_SIZE STACK_ADDRESS MIN_STACK_SIZE MIN_HEAP_SIZE EXT_RAM_SIZE FLASH_ORIGIN RAM_ORIGIN EXT_RAM_ORIGIN)
	CONFIGURE_FILE(${CMSIS_LINKER_SCRIPT} ${CMAKE_CURRENT_BINARY_DIR}/stm32${STM32_FAMILY_L}_flash.ld)
ENDFUNCTION(STM32_SET_PARAMS)

FUNCTION(STM32_SET_PARAMS FLASH_SIZE RAM_SIZE STACK_ADDRESS)
    SET(STACK_ADDRESS ${STACK_ADDRESS})
    SET(FLASH_SIZE ${FLASH_SIZE})
    SET(RAM_SIZE ${RAM_SIZE})
    SET(MIN_STACK_SIZE "0x200")
    SET(MIN_HEAP_SIZE "0")
    SET(EXT_RAM_SIZE "0K")
    SET(FLASH_ORIGIN "0x08000000")
    SET(RAM_ORIGIN "0x20000000")
    SET(EXT_RAM_ORIGIN "0x60000000")
    CONFIGURE_FILE(${CMSIS_LINKER_SCRIPT} ${CMAKE_CURRENT_BINARY_DIR}/stm32${STM32_FAMILY_L}_flash.ld)
ENDFUNCTION(STM32_SET_PARAMS)
